# Generated by Django 2.2.7 on 2019-12-15 21:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191215_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 21, 26, 31, 259272, tzinfo=utc)),
        ),
    ]
